# 错误处理

## 原生错误类型

-   Error
-   SyntaxError
-   ReferenceError
-   RangeError
-   TypeError
-   URIError
-   EvalError

## 自定义错误

```javascript
function UserError(message) {
    this.message = mssage;
    this.name = 'UserError';
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;

throw newUserError('这是自定义的错误！');
```

## throw 语句

用于手动中断程序，抛出错误。

## try...catch 结构

需要注意代码执行顺序。

```javascript
function fn() {
    console.log(0);
    try {
        console.log(1);
        throw Error('error happend');
    } catch {
        console.log(2);
        return true; // 执行完finally代码块后执行，但被finally里的return覆盖
        console.log(3);
    } finally {
        console.log(4);
        return false;
        console.log(5);
    }
    console.log(6);
}

fn();
// 0
// 1
// 2
// 4
// false
```
